### ISSUE TITLE
[Backoffice] Deploy nestjs

### ISSUE THREAD

**Issue by sgomez** [aulasoftwarelibre/ideas#33]

**Comment by victormonserrat** [comment]
I've created some useful common classes for modeling the domain in [08fd8e8](https://github.com/aulasoftwarelibre/ideas/commit/08fd8e831b44f5b3882afe41849441c2d4953698). Could you review it @sgomez @omarsotillo? :eyes: Thanks!

**Comment by sgomez** [comment]
But you already merget it @victormonserrat ...
